-- ============================================================
-- 1. USERS TABLE
-- ============================================================

create table if not exists public.users (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  avatar_url text,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.users enable row level security;

-- User can view their own profile
create policy "Users can view own profile"
on public.users for select
using (auth.uid() = id);

-- Public can view basic profile info
create policy "Public can view basics of users"
on public.users for select
using (true);

-- Only the user can update their own profile
create policy "Users can update own profile"
on public.users for update
using (auth.uid() = id);

-- Auto-create user row when auth user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();


-- ============================================================
-- 2. POSTS TABLE
-- ============================================================

create table if not exists public.posts (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  title text not null,
  content text not null,
  image_url text,
  tags text[], -- Array of strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.posts enable row level security;

-- Public can view all posts
create policy "Public posts are viewable by everyone"
on public.posts for select
using (true);

-- Only logged-in user can create a post
create policy "Users can create their own posts"
on public.posts for insert
with check (auth.uid() = user_id);

-- Only the author can update their post (ADDED THIS)
create policy "Users can update own posts"
on public.posts for update
using (auth.uid() = user_id);

-- Only the author can delete their post
create policy "Users can delete own posts"
on public.posts for delete
using (auth.uid() = user_id);


-- ============================================================
-- 3. COMMENTS TABLE
-- ============================================================

create table if not exists public.comments (
  id uuid default gen_random_uuid() primary key,
  post_id uuid references public.posts(id) on delete cascade not null,
  user_id uuid references public.users(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;

-- Public can view comments
create policy "Comments are viewable by everyone"
on public.comments for select
using (true);

-- Only logged-in user can add comment
create policy "Authenticated users can insert comments"
on public.comments for insert
with check (auth.uid() = user_id);

-- Only comment author can delete comment
create policy "Users can delete own comments"
on public.comments for delete
using (auth.uid() = user_id);

-- Only comment author can update comment (Optional but good to have)
create policy "Users can update own comments"
on public.comments for update
using (auth.uid() = user_id);


-- ============================================================
-- 4. FOLLOWERS TABLE
-- ============================================================

create table if not exists public.followers (
  id bigint generated by default as identity primary key,
  follower uuid references public.users(id) on delete cascade,
  following uuid references public.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.followers enable row level security;

-- Everyone can view followers/following counts
create policy "Followers are viewable by everyone"
on public.followers for select
using (true);

-- User can follow someone
create policy "User can follow another user"
on public.followers for insert
with check (auth.uid() = follower);

-- User can unfollow
create policy "User can unfollow"
on public.followers for delete
using (auth.uid() = follower);


-- ============================================================
-- 5. NOTIFICATIONS TABLE
-- ============================================================

create table if not exists public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  actor_id uuid references public.users(id) on delete cascade,
  type text not null, 
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc', now()) not null
);

alter table public.notifications enable row level security;

-- User can read own notifications
create policy "Users can read own notifications"
on public.notifications
for select
using (auth.uid() = user_id);

-- System can insert notifications (via triggers with security definer)
-- OR users trigger it indirectly. RLS check for insert:
create policy "System can insert notifications"
on public.notifications
for insert
with check (true); 

-- User can update own notifications (mark read)
create policy "Users can update own notifications"
on public.notifications
for update
using (auth.uid() = user_id);


-- ============================================================
-- 6. LIKES TABLE
-- ============================================================

create table if not exists public.likes (
  id uuid default gen_random_uuid() primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique (post_id, user_id)
);

alter table public.likes enable row level security;

create policy "Users can like posts"
on public.likes for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can unlike posts"
on public.likes for delete
to authenticated
using (auth.uid() = user_id);

create policy "Anyone can read likes"
on public.likes for select
using (true);


-- ============================================================
-- 7. SAVED POSTS TABLE
-- ============================================================

create table if not exists public.saved_posts (
  id uuid default gen_random_uuid() primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique (post_id, user_id)
);

alter table public.saved_posts enable row level security;

create policy "Users can save posts"
on public.saved_posts for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can unsave posts"
on public.saved_posts for delete
to authenticated
using (auth.uid() = user_id);

create policy "Users can view their own saved posts"
on public.saved_posts for select
to authenticated
using (auth.uid() = user_id);


-- ============================================================
-- TRIGGERS (NOTIFICATIONS)
-- ============================================================

-- 1. NEW FOLLOWERS
create or replace function public.handle_new_follower()
returns trigger as $$
begin
  insert into public.notifications (user_id, actor_id, type, message)
  values (new.following, new.follower, 'follow', 'started following you');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_new_follower on public.followers;
create trigger on_new_follower
after insert on public.followers
for each row execute procedure public.handle_new_follower();

-- 2. POST LIKES
create or replace function public.handle_new_like()
returns trigger as $$
declare
  post_author_id uuid;
begin
  select user_id into post_author_id from public.posts where id = new.post_id;
  if post_author_id is not null and post_author_id <> new.user_id then
    insert into public.notifications (user_id, actor_id, type, message)
    values (post_author_id, new.user_id, 'post', 'liked your post');
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_new_like on public.likes;
create trigger on_new_like
after insert on public.likes
for each row execute procedure public.handle_new_like();

-- 3. COMMENTS
create or replace function public.handle_new_comment()
returns trigger as $$
declare
  post_author_id uuid;
begin
  select user_id into post_author_id from public.posts where id = new.post_id;
  if post_author_id is not null and post_author_id <> new.user_id then
    insert into public.notifications (user_id, actor_id, type, message)
    values (post_author_id, new.user_id, 'post', 'commented on your post');
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_new_comment on public.comments;
create trigger on_new_comment
after insert on public.comments
for each row execute procedure public.handle_new_comment();

-- ============================================================
-- 8. USER LOGINS TABLE (For Login Activity)
-- ============================================================

create table if not exists public.user_logins (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  device_info text,
  last_login timestamptz default now()
);

-- Enable RLS
alter table public.user_logins enable row level security;

-- Policy: Users can see their own login history
create policy "Users can view own login history"
on public.user_logins for select
using ( auth.uid() = user_id );

-- Policy: Users can insert their own login history
create policy "Users can insert own login history"
on public.user_logins for insert
with check ( auth.uid() = user_id );

-- Policy: Users can delete their own login history (Added for 'Logout' button)
create policy "Users can delete own login history"
on public.user_logins for delete
using ( auth.uid() = user_id );
